version: '3.8'

services:
  btc-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: btc-service
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - TZ=UTC
